name: contact_angles
dependencies:
  - numpy==1.20.3
  - scipy==1.6.3
  - scikit-image==0.18.1
  - imageio==2.9.0
  - matplotlib==3.4.2
  - numba==0.53.1
  - pip
  - pip:
    - imageio-ffmpeg==0.4.4
    - pyautogui==0.9.52
